package com.mycompany.proyectofisica1;
import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ricardo
 */
public class Conversiones extends javax.swing.JFrame {

    /**
     * Creates new form Conversiones
     */
    public Conversiones() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Conversiones");

        jButton3.addActionListener((ActionEvent e) -> {
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[]{"Segundos", "Minutos", "Horas", "Días", "Años"}));
            jComboBox3.setModel(new DefaultComboBoxModel<>(new String[]{"Segundos", "Minutos", "Horas", "Días", "Años"}));
        });

        jButton4.addActionListener((ActionEvent e) -> {
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[]{"Metros", "Kilómetros", "Millas", "Pies", "Centímetros", "Pulgadas"}));
            jComboBox3.setModel(new DefaultComboBoxModel<>(new String[]{"Metros", "Kilómetros", "Millas", "Pies", "Centímetros", "Pulgadas"}));
        });

        jButton5.addActionListener((ActionEvent e) -> {
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[]{"Kilogramo", "Gramo", "Libra", "Onzas"}));
            jComboBox3.setModel(new DefaultComboBoxModel<>(new String[]{"Kilogramo", "Gramo", "Libra", "Onzas"}));
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jLabel1.setText("Elija que tipo de coversion desea usar");

        jButton2.setText("Convertir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jButton3.setText("Tiempo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Longitud");

        jButton5.setText("Masa");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Conversiones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jComboBox2, 0, 135, Short.MAX_VALUE)
                        .addGap(100, 100, 100)
                        .addComponent(jComboBox3, 0, 136, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton3)
                        .addGap(52, 52, 52)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    try{
            double numero1 = Double.parseDouble(jTextField1.getText());

            String seleccion1 = jComboBox2.getSelectedItem().toString();
            String seleccion2 = jComboBox3.getSelectedItem().toString();
            double resultado = 0.0;

            switch (seleccion1){
                //Tiempo
                case "Segundos" -> {
                    switch (seleccion2){
                        case "Segundos" -> resultado = numero1;
                        case "Minutos" -> resultado = numero1/60;
                        case "Horas" -> resultado = numero1/3600;
                        case "Días" -> resultado = numero1/86400;
                        case "Años" ->  resultado = numero1/3.154e+7;
                    }
                }
                case "Minutos" -> {
                    switch (seleccion2){
                        case "Segundos" -> resultado = numero1*60;
                        case "Minutos" -> resultado = numero1;
                        case "Horas" -> resultado = numero1/60;
                        case "Días" -> resultado = numero1/1440;
                        case "Años" -> resultado = numero1/525600;
                    }
                }
                case "Horas" -> {
                    switch (seleccion2){
                        case "Segundos" -> resultado = numero1*3600;
                        case "Minutos" -> resultado = numero1*60;
                        case "Horas" -> resultado = numero1;
                        case "Días" -> resultado = numero1/24;
                        case "Años" -> resultado = numero1/8760;
                    }
                }
                case "Días" -> {
                    switch (seleccion2){
                        case "Segundos" -> resultado = numero1*86400;
                        case "Minutos" -> resultado = numero1*1440;
                        case "Horas" -> resultado = numero1*24;
                        case "Días" -> resultado = numero1;
                        case "Años" -> resultado = numero1/365;
                    }
                }
                case "Años" -> {
                    switch (seleccion2){
                        case "Segundos" -> resultado = numero1*3.154e+7;
                        case "Minutos" ->resultado = numero1*525600;
                        case "Horas" -> resultado = numero1*8760;
                        case "Días" -> resultado = numero1*365;
                        case "Años" -> resultado = numero1;
                    }
                }
                //Longitud
                case "Metros" -> {
                    switch (seleccion2){
                        case "Metros" -> resultado = numero1;
                        case "Kilómetros" ->resultado = numero1/1000;
                        case "Millas" -> resultado = numero1/1609;
                        case "Pies" -> resultado = numero1*3.281;
                        case "Centímetros" -> resultado = numero1*100;
                        case "Pulgadas" -> resultado = numero1*39.37;
                    }
                }
                case "Kilómetros"->{
                    switch (seleccion2){
                        case "Metros" -> resultado = numero1 * 1000;
                        case "Kilómetros" -> resultado = numero1;
                        case "Millas" -> resultado = numero1 * 1e+12;
                        case "Pies" -> resultado = numero1 * 3281;
                        case "Centímetros" -> resultado = numero1 * 100000;
                        case "Pulgadas" -> resultado = numero1 * 39370;
                    }
                }
                case "Millas"->{
                    switch (seleccion2){
                        case "Metros" -> resultado = numero1 * 1609;
                        case "Kilómetros" -> resultado = numero1 * 1.609;
                        case "Millas" -> resultado = numero1;
                        case "Pies" -> resultado = numero1 * 5228;
                        case "Centímetros" -> resultado = numero1 * 160900;
                        case "Pulgadas" -> resultado = numero1 * 63360;
                    }
                }
                case "Pies"->{
                    switch(seleccion2){
                        case "Metros" -> resultado = numero1 / 3.281;
                        case "Kilómetros" -> resultado = numero1 / 3281;
                        case "Millas" -> resultado = numero1 / 5280;
                        case "Pies" -> resultado = numero1;
                        case "Centímetros" -> resultado = numero1 / 30.48;
                        case "Pulgadas" -> resultado = numero1 / 12;
                    }
                }
                case "Centímetros"->{
                    switch(seleccion2){
                        case "Metros" -> resultado = numero1 / 100;
                        case "Kilómetros" -> resultado = numero1 / 100000;
                        case "Millas" -> resultado = numero1 / 160900;
                        case "Pies" -> resultado = numero1 / 30.48;
                        case "Centímetros" -> resultado = numero1;
                        case "Pulgadas" -> resultado = numero1 / 2.54;
                    }
                }
                case "Pulgadas"->{
                    switch(seleccion2){
                        case "Metros" -> resultado = numero1 / 39.37;
                        case "Kilómetros" -> resultado = numero1 / 39370;
                        case "Millas" -> resultado = numero1 / 63360;
                        case "Pies" -> resultado = numero1 / 12;
                        case "Centímetros" -> resultado = numero1 / 2.54;
                        case "Pulgadas" -> resultado = numero1;
                    }
                }
                //Masa
                case "Kilogramo"->{
                    switch(seleccion2){
                        case "Kilogramo" -> resultado = numero1;
                        case "Gramo" -> resultado = numero1 * 1000;
                        case "Libra" -> resultado = numero1 * 2.205;
                        case "Onzas" -> resultado = numero1 * 35.274;
                    }
                }
                case "Gramo"->{
                    switch(seleccion2){
                        case "Kilogramo" -> resultado = numero1 / 1000;
                        case "Gramo" -> resultado = numero1;
                        case "Libra" -> resultado = numero1 / 453.6;
                        case "Onzas" -> resultado = numero1 / 28.35;
                    }
                }
                case "Libra"->{
                    switch(seleccion2){
                        case "Kilogramo" -> resultado = numero1 / 2.205;
                        case "Gramo" -> resultado = numero1 * 453.6;
                        case "Libra" -> resultado = numero1;
                        case "Onzas" -> resultado = numero1 * 16;
                    }
                }
                case "Onzas"->{
                    switch(seleccion2){
                        case "Kilogramo" -> resultado = numero1 / 35.274;
                        case "Gramo" -> resultado = numero1 * 28.35;
                        case "Libra" -> resultado = numero1 / 16;
                        case "Onzas" -> resultado = numero1;
                    }
                }
            }
                DecimalFormat df = new DecimalFormat("#.#########");
                String nuevoresultado = df.format(resultado);
                jTextField2.setText(String.valueOf(nuevoresultado));
            }
        catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Solo se admiten valores numericos");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        
        boolean numeros = key >= 48 && key <= 57;
        
        if(!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        
        boolean numeros = key >= 48 && key <= 57;
        
        if(!numeros){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped
                                                                                       

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        jTextField1.setText("");
        jTextField2.setText("");
    }                                           

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
