/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofisica1;

import java.awt.event.ActionEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ricardo
 */
public class MruMruv extends javax.swing.JFrame {

    /**
     * Creates new form MruMruv
     */
    public MruMruv() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("MRU y MRUV");

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[]{"Distancia", "Tiempo", "Velocidad",
            "Velocidad Media", "Velocidad Inicial", "Velocidad Final", "Aceleracion"
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Movimiento Rectilinio Uniforme y Uniformemente Variado");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Distancia:");

        jLabel3.setText("Tiempo:");

        jLabel4.setText("Velocidad:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jButton4.setText("Calcular");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Velocidad Final:");

        jLabel6.setText("Velocidad Inicial:");

        jLabel7.setText("Aceleracion:");

        jLabel8.setText("Velocidad Media:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jButton2.setText("Calcular usando Gravedad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Resultado:");

        jLabel10.setText("Selecciona la operacion que se desea realizar y acontinuacion llene los espacios con los valores que se tengan ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField7)
                                    .addComponent(jTextField8))))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(134, 134, 134))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addGap(30, 30, 30)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton1))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String opSelect = jComboBox1.getSelectedItem().toString();

        if (opSelect.equals("Velocidad")) {
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(false);
            jTextField4.setEditable(false);
            jTextField5.setEditable(false);
            jTextField6.setEditable(false);
            jTextField7.setEditable(false);
        }

        if (opSelect.equals("Aceleracion")) {
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(false);
            jTextField4.setEditable(false);
            jTextField5.setEditable(true);
            jTextField6.setEditable(true);
            jTextField7.setEditable(false);
        }

        if (opSelect.equals("Distancia")) {
            jTextField1.setEditable(false);
            jTextField2.setEditable(true);
            jTextField3.setEditable(true);
            jTextField4.setEditable(false);
            jTextField5.setEditable(true);
            jTextField6.setEditable(true);
            jTextField7.setEditable(true);
        }

        if (opSelect.equals("Tiempo")) {
            jTextField1.setEditable(true);
            jTextField2.setEditable(false);
            jTextField3.setEditable(true);
            jTextField4.setEditable(false);
            jTextField5.setEditable(true);
            jTextField6.setEditable(true);
            jTextField7.setEditable(true);
        }

        if (opSelect.equals("Velocidad Media")) {
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            jTextField3.setEditable(false);
            jTextField4.setEditable(false);
            jTextField5.setEditable(true);
            jTextField6.setEditable(true);
            jTextField7.setEditable(false);
        }

        if (opSelect.equals("Velocidad Inicial")) {
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(false);
            jTextField4.setEditable(true);
            jTextField5.setEditable(true);
            jTextField6.setEditable(false);
            jTextField7.setEditable(true);
        }

        if (opSelect.equals("Velocidad Final")) {
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
            jTextField3.setEditable(false);
            jTextField4.setEditable(true);
            jTextField5.setEditable(false);
            jTextField6.setEditable(true);
            jTextField7.setEditable(true);
        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String opSelect = jComboBox1.getSelectedItem().toString();

        double vo = 0.0;
        double vf = 0.0;
        double vm = 0.0;
        double v = 0.0;
        double d = 0.0;
        double t = 0.0;
        double a = 0.0;
        double g = 9.8;
        boolean validInput = true;

        if (!jTextField1.getText().isEmpty()) {
            d = Double.parseDouble(jTextField1.getText());
        }
        if (!jTextField2.getText().isEmpty()) {
            t = Double.parseDouble(jTextField2.getText());
        }
        if (!jTextField3.getText().isEmpty()) {
            v = Double.parseDouble(jTextField3.getText());
        }
        if (!jTextField4.getText().isEmpty()) {
            vm = Double.parseDouble(jTextField4.getText());
        }
        if (!jTextField5.getText().isEmpty()) {
            vf = Double.parseDouble(jTextField5.getText());
        }
        if (!jTextField6.getText().isEmpty()) {
            vo = Double.parseDouble(jTextField6.getText());
        }
        if (!jTextField7.getText().isEmpty()) {
            a = Double.parseDouble(jTextField7.getText());
        }

        if (opSelect.equals("Distancia")) {      
      
            //else {
                //JOptionPane.showMessageDialog(this, "No se encontraron suficientes datos para operar", "Error", JOptionPane.INFORMATION_MESSAGE);
           // }
            // Calcular distancia si no está aceleracion
            try{
                if (jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                d = t * ((vf + vo) / 2);
                jTextField8.setText(String.format("%.2f", d));
                JOptionPane.showMessageDialog(this, "La distancia es: " + String.format("%.2f", d) + " m\n" + "La formula empleada es:\n" + "d = ((vf+vo)/2)t", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: Por favor, ingrese valores numéricos en todos los campos.");
        }

            // Calcular distancia si no esta el tiempo
            try{
            if (jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField2.getText().isEmpty()) {
                d = ((vf * vf) - (vo * vo)) / (2 * a);
                jTextField8.setText(String.format("%.2f", d));
                JOptionPane.showMessageDialog(this, "La distancia es: " + String.format("%.2f", d) + " m\n" + "La formula empleada es:\n" + "d = (vf²-vo²) / 2a", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: Por favor, ingrese valores numéricos en todos los campos.");
        }

            // Calcular distancia solo con tiempo y velocidad
            try{
            if (jTextField1.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField5.getText().isEmpty() && jTextField6.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                d = v * t;
                jTextField8.setText(String.format("%.2f", d));
                JOptionPane.showMessageDialog(this, "La distancia es: " + String.format("%.2f", d) + " m\n" + "La formula empleada es:\n" + "d = vt", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: Por favor, ingrese valores numéricos en todos los campos.");
        }
            validInput = false;
        }

        if (opSelect.equals("Tiempo")) {
            // Calcular tiempo solo con distancia y velocidad
            try{
            if (jTextField2.getText().isEmpty() && jTextField5.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField7.getText().isEmpty() && jTextField6.getText().isEmpty()) {
                t = v / d;
                jTextField8.setText(String.format("%.2f", t));
                JOptionPane.showMessageDialog(this, "El tiempo es: " + String.format("%.2f", t) + " s\n" + "La formula empleada es:\n" + "t = v / d", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: Por favor, ingrese valores numéricos en todos los campos.");
        }

            // Calcular tiempo sin aceleracion
            try{
            if (jTextField2.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField7.getText().isEmpty() && jTextField3.getText().isEmpty()) {
                t = (2 * d) / (vf + vo) ;
                jTextField8.setText(String.format("%.2f", t));
                JOptionPane.showMessageDialog(this, "El tiempo es: " + String.format("%.2f", t) + " s\n" + "La formula empleada es:\n" + "", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: Por favor, ingrese valores numéricos en todos los campos.");
        }

            // Calcular tiempo sin distancia
            try{
            if (jTextField2.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty()) {
                t = (vf - vo) / a;
                jTextField8.setText(String.format("%.2f", t));
                JOptionPane.showMessageDialog(this, "El tiempo es: " + String.format("%.2f", t) + " s\n" + "La formula empleada es:\n" + "t = (vf - vo) / a", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
            } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: Por favor, ingrese valores numéricos en todos los campos.");
        }
            validInput = false;
        }

            if (opSelect.equals("Velocidad")) {

            // Calcular la velocidad
            if (jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField5.getText().isEmpty() && jTextField6.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                v = d / t;
                jTextField8.setText(String.format("%.2f", v));
                JOptionPane.showMessageDialog(this, "La velocidad es: " + String.format("%.2f", v) + " s\n" + "La formula empleada es:\n" + "v = d / t", "Resultado", JOptionPane.INFORMATION_MESSAGE);                
                }
            validInput = false;
            }

            if (opSelect.equals("Velocidad Media")) {
                // Calcular la velocidad media
                if (jTextField1.getText().isEmpty() && jTextField2.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                    vm = (vf + vo) / 2;
                    jTextField8.setText(String.format("%.2f", vm));
                    JOptionPane.showMessageDialog(this, "La velocidad es: " + String.format("%.2f", vm) + " s\n" + "La formula empleada es:\n" + "vm = (vf + vo) / 2", "Resultado", JOptionPane.INFORMATION_MESSAGE);                    
                }
            validInput = false;
            }

            if (opSelect.equals("Aceleracion")) {
                // Calcular la aceleracion sin distanciavo
                if (jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                    a = (vf - vo) / t;
                    jTextField8.setText(String.format("%.2f", a));
                    JOptionPane.showMessageDialog(this, "La aceleracion es: " + String.format("%.2f", a) + " m/s²\n" + "La formula empleada es:\n" + "a = (vf-vo) / t", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }

                // Calcular la aceleracion sin tiempo
                if (jTextField2.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                    a = (((vf * vf) - (vo * vo)) / (2 * d));
                    jTextField8.setText(String.format("%.2f", a));
                    JOptionPane.showMessageDialog(this, "La aceleracion es: " + String.format("%.2f", a) + " m/s²\n" + "La formula empleada es:\n" + "a = (vf²-vo²) / 2d", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }
                validInput = false;
            }

            if (opSelect.equals("Velocidad Final")) {
                // Calcular la velocidad final con aceleracion
                if (jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField5.getText().isEmpty()) {
                    vf = (a * t) + vo;
                    jTextField8.setText(String.format("%.2f", vf));
                    JOptionPane.showMessageDialog(this, "La Velocidad Final es: " + String.format("%.2f", vf) + " m/s\n" + "La formula empleada es:\n" + "vf = at + vo", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }

                // Calcular la velocidad final con tiempo
                if (jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField5.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                    vf = ((d * 2) / t) - vo;
                    jTextField8.setText(String.format("%.2f", vf));
                    JOptionPane.showMessageDialog(this, "La Velocidad Final es: " + String.format("%.2f", vf) + " m/s\n" + "La formula empleada es:\n" + "vf = 2d/t - vo", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }

                // Calcular la velocidad final con velocidad media
                if (jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField2.getText().isEmpty() && jTextField5.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                    vf = (2 * vm) - vo;
                    jTextField8.setText(String.format("%.2f", vf));
                    JOptionPane.showMessageDialog(this, "La Velocidad Final es: " + String.format("%.2f", vf) + " m/s\n" + "La formula empleada es:\n" + "vf = 2vm -vo", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }

                // Calcular la velocidad final con distancia
                if (jTextField2.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField5.getText().isEmpty()) {
                    vf = Math.sqrt((2 * a * d) + (vo * vo));
                    jTextField8.setText(String.format("%.2f", vf));
                    JOptionPane.showMessageDialog(this, "La Velocidad Final es: " + String.format("%.2f", vf) + " m/s\n" + "La formula empleada es:\n" + "vf = √(2ad + vo²)", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }
                validInput = false;
            }

            if (opSelect.equals("Velocidad Inicial")) {
                // Calcular la velocidad final con aceleracion
                if (jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField6.getText().isEmpty() && jTextField6.getText().isEmpty()) {
                    vo = vf - (a * t);
                    jTextField8.setText(String.format("%.2f", vo));
                    JOptionPane.showMessageDialog(this, "La velocidad inicial es: " + String.format("%.2f", vo) + " m/s\n" + "La formula empleada es:\n" + "vo = at - vf", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }

                // Calcular la velocidad final con tiempo
                if (jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField6.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                    vo = ((2 * d) / t) - vf;
                    jTextField8.setText(String.format("%.2f", vo));
                    JOptionPane.showMessageDialog(this, "La velocidad inicial es: " + String.format("%.2f", vo) + " m/s\n" + "La formula empleada es:\n" + "vo = 2d/t - vf", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }

                // Calcular la velocidad final con velocidad media
                if (jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField2.getText().isEmpty() && jTextField6.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                    vo = (2 * vm) - vf;
                    jTextField8.setText(String.format("%.2f", vo));
                    JOptionPane.showMessageDialog(this, "La Velocidad inicial es: " + String.format("%.2f", vo) + " m/s\n" + "La formula empleada es:\n" + "vo = 2mv - vf", "Resultado", JOptionPane.INFORMATION_MESSAGE);
                }

                // Calcular la velocidad final con distancia
                if (jTextField2.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField6.getText().isEmpty()) {
                    vo = Math.sqrt((2 * a * d) - (vf * vf));
                    jTextField8.setText(String.format("%.2f", vo));
                    JOptionPane.showMessageDialog(this, "La velocidad inicial es: " + String.format("%.2f", vo) + " m/s\n" + "La formula empleada es:\n" + "vo = √(2ad - vf²)", "Resultado", JOptionPane.INFORMATION_MESSAGE);                    
                } 
            
            validInput = false;
                
            }
            
            
if (!validInput) {
            JOptionPane.showMessageDialog(this, "Datos ingresados erroneamente", "Error", JOptionPane.ERROR_MESSAGE);
        }    


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 46 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 46 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 46 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 46 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 46 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 46 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 46 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String opSelect = jComboBox1.getSelectedItem().toString();

        boolean validInput = false;
        double vo = 0.0;
        double vf = 0.0;
        double vm = 0.0;
        double v = 0.0;
        double d = 0.0;
        double t = 0.0;
        double a = 0.0;
        double g = 9.8;

        if (!jTextField1.getText().isEmpty()) {
            d = Double.parseDouble(jTextField1.getText());
        }
        if (!jTextField2.getText().isEmpty()) {
            t = Double.parseDouble(jTextField2.getText());
        }
        if (!jTextField3.getText().isEmpty()) {
            v = Double.parseDouble(jTextField3.getText());
        }
        if (!jTextField4.getText().isEmpty()) {
            vm = Double.parseDouble(jTextField4.getText());
        }
        if (!jTextField5.getText().isEmpty()) {
            vf = Double.parseDouble(jTextField5.getText());
        }
        if (!jTextField6.getText().isEmpty()) {
            vo = Double.parseDouble(jTextField6.getText());
        }
        if (!jTextField7.getText().isEmpty()) {
            a = Double.parseDouble(jTextField7.getText());
        }

        if (opSelect.equals("Distancia")) {
            // Calcular distancia si no esta la aceleracion, velocidad inicial y con gravedad
            if (jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField7.getText().isEmpty() && jTextField6.getText().isEmpty()) {
                d = (vf * t) + (0.5 * (g * (t * t)));
                jTextField8.setText(String.format("%.2f", d));
                JOptionPane.showMessageDialog(this, "La distancia es: " + String.format("%.2f", d) + " m\n" + "La formula empleada es:\n" + "d = vft + 1/2gt²", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }

            // Calcular distancia si no esta la aceleracion, velocidad final y con gravedad
            if (jTextField1.getText().isEmpty() && jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField7.getText().isEmpty() && jTextField5.getText().isEmpty()) {
                d = (vo * t) - (0.5 * (g * (t * t)));
                jTextField8.setText(String.format("%.2f", d));
                JOptionPane.showMessageDialog(this, "La distancia es: " + String.format("%.2f", d) + " m\n" + "La formula empleada es:\n" + "d = vot - 1/2gt²", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
                validInput = false;
        }

        if (opSelect.equals("Velocidad Final")) {
            // Calcular la velocidad final con distancia, gravedad y tiempo
            if (jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField5.getText().isEmpty() && jTextField6.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                vf = (d / t) - (0.5 * g * t);
                jTextField8.setText(String.format("%.2f", vf));
                JOptionPane.showMessageDialog(this, "La velocidad final es: " + String.format("%.2f", vf) + " m/s\n" + "La formula empleada es:\n" + "vf = d/t + 1/2gt", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
        }

        if (opSelect.equals("Velocidad Inicial")) {
            // Calcular la velocidad final con distancia, gravedad y tiempo
            if (jTextField3.getText().isEmpty() && jTextField4.getText().isEmpty() && jTextField5.getText().isEmpty() && jTextField6.getText().isEmpty() && jTextField7.getText().isEmpty()) {
                vo = (d / t) + (0.5 * g * t);
                jTextField8.setText(String.format("%.2f", vo));
                JOptionPane.showMessageDialog(this, "La velocidad inicial es: " + String.format("%.2f", vo) + " m/s\n" + "La formula empleada es:\n" + "vo = d/t + 1/2gt", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            }
                validInput = false;
        }
        
if (!validInput) {
            JOptionPane.showMessageDialog(this, "Datos ingresados erroneamente", "Error", JOptionPane.ERROR_MESSAGE);
        }    

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
